
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Kusach
{

using System;
    using System.Collections.Generic;
    
public partial class Dispatcher
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Dispatcher()
    {

        this.RouteList = new HashSet<RouteList>();

    }


    public int IdDispatcher { get; set; }

    public string Login { get; set; }

    public string Password { get; set; }

    public string FName { get; set; }

    public string LName { get; set; }

    public string MName { get; set; }

    public System.DateTime Birthday { get; set; }

    public string PhoneNumber { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RouteList> RouteList { get; set; }

}

}
